# Generated by Django 5.1.3 on 2025-12-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(max_length=6)),
                ('pere', models.CharField(blank=True, max_length=500, null=True)),
                ('mere', models.CharField(blank=True, max_length=500, null=True)),
                ('situation_maritale', models.CharField(max_length=15)),
                ('diplome_experience', models.TextField()),
                ('adresse', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.IntegerField()),
                ('departement', models.CharField(max_length=250)),
                ('poste', models.CharField(max_length=250)),
                ('matricule', models.IntegerField(unique=True)),
                ('date_embauche', models.DateField()),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(unique=True, upload_to='users/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
