# Generated by Django 5.1.3 on 2026-01-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0002_employe_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='poste',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='departement',
            new_name='unite',
        ),
    ]
