# Generated by Django 5.1.3 on 2026-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0003_rename_poste_employe_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='unite_ancien',
            field=models.CharField(default='Antigang', max_length=250),
        ),
        migrations.AlterField(
            model_name='employe',
            name='grade',
            field=models.CharField(default='Soldat', max_length=250),
        ),
    ]
