# Generated by Django 5.1.3 on 2026-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0004_employe_unite_ancien_alter_employe_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='grade',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employe',
            name='unite_ancien',
            field=models.CharField(max_length=250),
        ),
    ]
