# Generated by Django 5.1.3 on 2026-01-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0005_alter_employe_grade_alter_employe_unite_ancien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(upload_to='empoloye/'),
        ),
    ]
