# Generated by Django 5.1.3 on 2026-01-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0006_alter_employe_email_alter_employe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
