# Generated by Django 5.1.3 on 2026-01-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0007_alter_employe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='photo',
            field=models.ImageField(upload_to='employe/'),
        ),
    ]
