# Generated by Django 5.1.3 on 2026-01-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_RH', '0008_alter_employe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='categorie_grade',
            field=models.CharField(choices=[('Haut gradé', 'Haut gradé'), ('Sous-officier', 'Sous-officier'), ('Militaire du rang', 'Militaire du rang')], default='Militaire du rang', editable=False, max_length=20),
        ),
    ]
